//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RequirementsCompiler {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/modules.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/modules.xsd", IsNullable=false)]
    public partial class Modules {
        
        private Module[] moduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Module")]
        public Module[] Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public partial class Module {
        
        private string nameField;
        
        private Status statusField;
        
        private Priority priorityField;
        
        private string versionField;
        
        private License licenseField;
        
        private string overviewField;
        
        private ModuleFeature[] featuresField;
        
        private ModuleTechnology[] technologiesField;
        
        private string[] dependenciesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public License License {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        public string Overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Feature", IsNullable=false)]
        public ModuleFeature[] Features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Technology", IsNullable=false)]
        public ModuleTechnology[] Technologies {
            get {
                return this.technologiesField;
            }
            set {
                this.technologiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dependency", IsNullable=false)]
        public string[] Dependencies {
            get {
                return this.dependenciesField;
            }
            set {
                this.dependenciesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public enum Status {
        
        /// <remarks/>
        Proposed,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pre-Alpha")]
        PreAlpha,
        
        /// <remarks/>
        Alpha,
        
        /// <remarks/>
        Beta,
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        Obsolete,
        
        /// <remarks/>
        Depricated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("On Hold")]
        OnHold,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public enum Priority {

        /// <remarks/>
        Urgent,

        /// <remarks/>
        High,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        TBD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public enum License {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Open-Source")]
        OpenSource,
        
        /// <remarks/>
        Scaffeine,
        
        /// <remarks/>
        Proprietary,
        
        /// <remarks/>
        TBD,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/modules.xsd")]
    public partial class ModuleFeature {
        
        private string nameField;
        
        private string descriptionField;
        
        private Area areaField;
        
        private Priority priorityField;
        
        private int remainingField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Area Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public int Remaining {
            get {
                return this.remainingField;
            }
            set {
                this.remainingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public enum Area {
        
        /// <remarks/>
        Development,
        
        /// <remarks/>
        Analysis,
        
        /// <remarks/>
        Testing,
        
        /// <remarks/>
        Architecture,
        
        /// <remarks/>
        Design,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/modules.xsd")]
    public partial class ModuleTechnology {
        
        private string nameField;
        
        private Expertise expertiseField;
        
        private Workload workloadField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Expertise Expertise {
            get {
                return this.expertiseField;
            }
            set {
                this.expertiseField = value;
            }
        }
        
        /// <remarks/>
        public Workload Workload {
            get {
                return this.workloadField;
            }
            set {
                this.workloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public enum Expertise {
        
        /// <remarks/>
        Expert,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mid-Level")]
        MidLevel,

        /// <remarks/>
        Novice,                
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/modules.xsd")]
    public enum Workload {
        
        /// <remarks/>
        Heavy,
        
        /// <remarks/>
        Light,
        
        /// <remarks/>
        Average,
    }
}
